version: '2'
services:
  web: 
    restart: always
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - /var/www
    ports:
      - "8086:80"
    links:
      - app
    depends_on:
      - app
      - db
      - cache

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - /var/www
    links:
      - db
    environment:
      - "DB_HOST=3306"
      - "DB_HOST=db"

  db:
    image: mysql:5.7
    volumes:
      - ./../mysql_data:/var/lib/mysql
      - ./:/var/www
    environment:
      - "MYSQL_ROOT_PASSWORD=Dbadmin@hng1!"
      - "MYSQL_DATABASE=transfer"
    ports:
      - "33072:3306"

  cache:
    image: redis:latest

