version: '2'

services:
  web: 
    restart: always
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - /var/www
    ports:
      - "8081:80"
    links:
      - app
    depends_on:
      - app
      - db
      - cache
    networks: 
      base:
        ipv4_address: 173.30.0.2

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - /var/www
    links:
      - db
    environment:
      - "DB_HOST=3306"
      - "DB_HOST=db"
    networks: 
      base:
        ipv4_address: 173.30.0.3
  db:
    image: mysql:5.7
    volumes:
      - ./../mysql_data:/var/lib/mysql
      - ./:/var/www
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=namedb"
    ports:
      - "33071:3306"
    networks: 
      base:
        ipv4_address: 173.30.0.4 

  cache:
    image: redis:latest
    networks: 
      base:
        ipv4_address: 173.30.0.5 

networks:
    base:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 173.30.0.0/16
              gateway: 173.30.0.100